name: Run benchmark comparison

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  benchmark-compare:
    runs-on: ubuntu-latest
    # TODO
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/benchmark-compare ')}}
    steps:
      - uses: TheModdingInquisition/actions-team-membership@v1.0
        with:
          team: 'team'
          organization: angular
          token: ${{secrets.ANGULAR_ROBOT_ACCESS_TOKEN}}
          exit: true

      - uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
        with:
          # Checkout the pull request and assume it being trusted given we've checked
          # that the action was triggered by a team member.
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - uses: ./.github/actions/yarn-install

      - uses: angular/dev-infra/github-actions/setup-bazel-remote-exec@5f06c4774df908ed69e1441f4ec63b898acf0c68
        with:
          bazelrc: ./.bazelrc.user

      - run: yarn benchmarks run-compare main //modules/benchmarks/src/expanding_rows:perf
        name: Running benchmark
